apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast0001-bad
  annotations:
    volume.beta.kubernetes.io/storage-class: fast-bad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
