apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast0001-bad
  annotations:
    storageClassName: fast-bad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
