apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc0001
  labels:
    environment: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast
